[project]
name = "cpp-here"
version = "0.2.0"
description = "An interactive command line tool for creating new CMake-based C++ projects quickly and effortlessly."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "questionary>=2.1.0",
    "stringcase>=1.2.0",
]
